# Generated by Django 2.2.6 on 2019-10-25 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superfield', models.BooleanField()),
                ('field_name', models.CharField(max_length=30)),
                ('date_now', models.DateField(auto_now=True)),
                ('custom_date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('field_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(max_length=254)),
                ('field_file', models.FileField(upload_to='')),
                ('field_image', models.ImageField(upload_to='')),
                ('field_year', models.IntegerField()),
                ('field_description', models.TextField()),
                ('field_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
