# Generated by Django 2.2.6 on 2019-10-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_sportsman_photo'),
        ('fields', '0003_auto_20191028_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfields',
            name='user',
        ),
        migrations.AddField(
            model_name='myfields',
            name='sportsman',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='sport.Sportsman'),
            preserve_default=False,
        ),
    ]
