# Generated by Django 2.2.6 on 2019-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindofsport',
            name='sportsmen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sportsman',
        ),
        migrations.AddField(
            model_name='sportsman',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsman',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsman',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsman',
            name='gym_name',
            field=models.CharField(default='asd', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsman',
            name='kind',
            field=models.CharField(choices=[('Street Workout', 'Street Workout'), ('Athletics', 'Athletics'), ('Power Lifting', 'Power Lifting'), ('ESports', 'ESports')], default='asd', max_length=20, verbose_name='Kind of sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsman',
            name='size',
            field=models.CharField(choices=[('Big', 'Big'), ('Medium', 'Medium'), ('Small', 'Small')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
        migrations.DeleteModel(
            name='KindOfSport',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
