# Generated by Django 2.2.6 on 2019-10-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20191028_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='gym_name',
        ),
    ]
