# Generated by Django 2.2.6 on 2019-10-23 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product name')),
                ('add_date', models.DateField(verbose_name='Add date')),
                ('date_of_expire', models.DateField(verbose_name='Date of expire')),
                ('product_photo', models.ImageField(upload_to='shop/images', verbose_name='Product photo')),
                ('expired', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, verbose_name='About Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
